
{
  "execution_mode": true,
  "product": {
    "avg_loan": 1.0,
    "apr_by_term": { "3": 0.12, "6": 0.14, "12": 0.18, "24": 0.22 },
    "lgd": 0.75,
    "recovery_rate": 0.50,
    "recovery_lag_months": 3
  },
  "segments": [
    { "name": "prime", "share": 0.55, "delinq_mult": 0.75, "prepay_mult": 1.6 },
    { "name": "nearprime", "share": 0.30, "delinq_mult": 1.00, "prepay_mult": 1.0 },
    { "name": "subprime", "share": 0.15, "delinq_mult": 1.35, "prepay_mult": 0.6 }
  ],
  "term_mix": { "3": 0.15, "6": 0.25, "12": 0.45, "24": 0.15 },
  "prepay_by_term": { "3": 0.020, "6": 0.012, "12": 0.008, "24": 0.006 },
  "delinquency": {
    "p_cur_to_30": 0.018,
    "p_30_to_60": 0.35,
    "p_60_to_90": 0.42,
    "p_90_to_def": 0.58,
    "p_30_cure": 0.25,
    "p_60_cure": 0.15,
    "p_90_cure": 0.08
  },
  "base_funnel": {
    "default_base_apps": 20000,
    "default_base_approval": 0.45,
    "default_base_takeup": 0.85,
    "base_apps_by_model": {
      "A_Vendor": 60000,
      "C_BankModel": 22000,
      "D_Embedded": 30000,
      "G_RiskShare": 22000,
      "H_Purchase": 18000,
      "I_Licensed": 15000
    },
    "base_approval_by_model": {
      "A_Vendor": 0.55,
      "C_BankModel": 0.45,
      "D_Embedded": 0.43,
      "G_RiskShare": 0.45,
      "H_Purchase": 0.42,
      "I_Licensed": 0.38
    },
    "base_takeup_by_model": {
      "A_Vendor": 0.0,
      "C_BankModel": 0.86,
      "D_Embedded": 0.88,
      "G_RiskShare": 0.86,
      "H_Purchase": 0.84,
      "I_Licensed": 0.82
    }
  },
  "model_fixed_multiplier": {
    "A_Vendor": 1.0,
    "C_BankModel": 2.2,
    "D_Embedded": 3.0,
    "G_RiskShare": 2.8,
    "H_Purchase": 4.0,
    "I_Licensed": 5.5
  },
  "regime_fixed_multiplier": {
    "Central": 1.0,
    "Stress_Ops": 1.25,
    "Stress_Partner": 1.15,
    "Stress_Macro": 1.10,
    "Stress_User": 1.30
  },
  "overhead": {
    "sticky_enabled": true,
    "ops_fixed_uplift": 0.25,
    "partner_fixed_uplift": 0.15,
    "decay_months": 3,
    "apply_to_support": true,
    "apply_to_complaints": true
  },
  "models": [
    {
      "name": "A_Vendor",
      "fee_per_app": 0.00020,
      "fee_per_funded": 0.0,
      "servicing_fee_rate_on_collections": 0.0,
      "nim_share": 0.0,
      "fixed_cost_monthly_loans": 1.0,
      "var_cost_per_app": 0.00001,
      "var_cost_per_funded": 0.0,
      "support_cost_per_active_loan": 0.0,
      "complaints_cost_per_complaint": 0.0005,
      "credit_exposure_share": 0.0,
      "first_loss_cap_pct_outstanding": 0.0,
      "depends_on_bank": true,
      "depends_on_merchant": false,
      "partner_hazard_annual": 0.08,
      "partner_volume_haircut": 0.35,
      "partner_event_duration_months": 3,
      "ops_hazard_monthly": 0.03,
      "ops_duration_months": 1,
      "ops_volume_haircut": 0.60,
      "ops_collections_drop": 0.0,
      "ops_pd_mult": 1.0
    },
    {
      "name": "C_BankModel",
      "fee_per_app": 0.00010,
      "fee_per_funded": 0.012,
      "servicing_fee_rate_on_collections": 0.0015,
      "nim_share": 0.0,
      "fixed_cost_monthly_loans": 1.0,
      "var_cost_per_app": 0.00006,
      "var_cost_per_funded": 0.0010,
      "support_cost_per_active_loan": 0.0003,
      "complaints_cost_per_complaint": 0.0012,
      "credit_exposure_share": 0.0,
      "first_loss_cap_pct_outstanding": 0.0,
      "depends_on_bank": true,
      "depends_on_merchant": false,
      "partner_hazard_annual": 0.12,
      "partner_volume_haircut": 0.15,
      "partner_event_duration_months": 5,
      "ops_hazard_monthly": 0.05,
      "ops_duration_months": 2,
      "ops_volume_haircut": 0.55,
      "ops_collections_drop": 0.25,
      "ops_pd_mult": 1.4
    },
    {
      "name": "D_Embedded",
      "fee_per_app": 0.00008,
      "fee_per_funded": 0.010,
      "servicing_fee_rate_on_collections": 0.0010,
      "nim_share": 0.0,
      "fixed_cost_monthly_loans": 1.0,
      "var_cost_per_app": 0.00005,
      "var_cost_per_funded": 0.0012,
      "support_cost_per_active_loan": 0.00025,
      "complaints_cost_per_complaint": 0.0013,
      "credit_exposure_share": 0.0,
      "first_loss_cap_pct_outstanding": 0.0,
      "depends_on_bank": true,
      "depends_on_merchant": true,
      "partner_hazard_annual": 0.14,
      "partner_volume_haircut": 0.10,
      "partner_event_duration_months": 6,
      "ops_hazard_monthly": 0.06,
      "ops_duration_months": 2,
      "ops_volume_haircut": 0.65,
      "ops_collections_drop": 0.30,
      "ops_pd_mult": 1.5
    },
    {
      "name": "G_RiskShare",
      "fee_per_app": 0.00010,
      "fee_per_funded": 0.016,
      "servicing_fee_rate_on_collections": 0.0015,
      "nim_share": 0.0,
      "fixed_cost_monthly_loans": 1.0,
      "var_cost_per_app": 0.00006,
      "var_cost_per_funded": 0.0011,
      "support_cost_per_active_loan": 0.00035,
      "complaints_cost_per_complaint": 0.0013,
      "credit_exposure_share": 0.0,
      "first_loss_cap_pct_outstanding": 0.05,
      "depends_on_bank": true,
      "depends_on_merchant": false,
      "partner_hazard_annual": 0.12,
      "partner_volume_haircut": 0.15,
      "partner_event_duration_months": 5,
      "ops_hazard_monthly": 0.05,
      "ops_duration_months": 2,
      "ops_volume_haircut": 0.55,
      "ops_collections_drop": 0.25,
      "ops_pd_mult": 1.5
    },
    {
      "name": "H_Purchase",
      "fee_per_app": 0.00005,
      "fee_per_funded": 0.007,
      "servicing_fee_rate_on_collections": 0.0010,
      "nim_share": 0.40,
      "fixed_cost_monthly_loans": 1.0,
      "var_cost_per_app": 0.00007,
      "var_cost_per_funded": 0.0015,
      "support_cost_per_active_loan": 0.0005,
      "complaints_cost_per_complaint": 0.0016,
      "credit_exposure_share": 0.80,
      "first_loss_cap_pct_outstanding": 0.0,
      "depends_on_bank": true,
      "depends_on_merchant": false,
      "partner_hazard_annual": 0.10,
      "partner_volume_haircut": 0.20,
      "partner_event_duration_months": 4,
      "ops_hazard_monthly": 0.05,
      "ops_duration_months": 2,
      "ops_volume_haircut": 0.55,
      "ops_collections_drop": 0.25,
      "ops_pd_mult": 1.4
    },
    {
      "name": "I_Licensed",
      "fee_per_app": 0.0,
      "fee_per_funded": 0.0,
      "servicing_fee_rate_on_collections": 0.0,
      "nim_share": 0.85,
      "fixed_cost_monthly_loans": 1.0,
      "var_cost_per_app": 0.00008,
      "var_cost_per_funded": 0.0018,
      "support_cost_per_active_loan": 0.0008,
      "complaints_cost_per_complaint": 0.0019,
      "credit_exposure_share": 1.0,
      "first_loss_cap_pct_outstanding": 0.0,
      "depends_on_bank": false,
      "depends_on_merchant": false,
      "partner_hazard_annual": 0.03,
      "partner_volume_haircut": 0.50,
      "partner_event_duration_months": 3,
      "ops_hazard_monthly": 0.04,
      "ops_duration_months": 2,
      "ops_volume_haircut": 0.55,
      "ops_collections_drop": 0.20,
      "ops_pd_mult": 1.3
    }
  ],
  "scenarios": [
    { "name": "Central", "months": 24, "macro_rho": 0.70, "macro_sigma": 0.35, "macro_pd_mult": 1.0, "macro_lgd_mult": 1.0, "macro_prepay_mult": 1.0, "bank_risk_appetite_mult": 1.0, "demand_mult": 1.0, "user_conversion_mult": 1.0, "user_delinquency_mult": 1.0, "complaints_mult": 1.0, "funding_spread_bps": 0 },
    { "name": "Stress_Ops", "months": 24, "macro_rho": 0.70, "macro_sigma": 0.35, "macro_pd_mult": 1.05, "macro_lgd_mult": 1.0, "macro_prepay_mult": 0.95, "bank_risk_appetite_mult": 1.0, "demand_mult": 1.0, "user_conversion_mult": 0.95, "user_delinquency_mult": 1.10, "complaints_mult": 1.35, "funding_spread_bps": 50 },
    { "name": "Stress_Partner", "months": 24, "macro_rho": 0.72, "macro_sigma": 0.35, "macro_pd_mult": 1.05, "macro_lgd_mult": 1.0, "macro_prepay_mult": 0.95, "bank_risk_appetite_mult": 0.92, "demand_mult": 0.95, "user_conversion_mult": 0.95, "user_delinquency_mult": 1.05, "complaints_mult": 1.15, "funding_spread_bps": 75 },
    { "name": "Stress_Macro", "months": 24, "macro_rho": 0.85, "macro_sigma": 0.55, "macro_pd_mult": 1.70, "macro_lgd_mult": 1.20, "macro_prepay_mult": 0.85, "bank_risk_appetite_mult": 0.78, "demand_mult": 1.10, "user_conversion_mult": 0.90, "user_delinquency_mult": 1.25, "complaints_mult": 1.20, "funding_spread_bps": 200 },
    { "name": "Stress_User", "months": 24, "macro_rho": 0.70, "macro_sigma": 0.35, "macro_pd_mult": 1.20, "macro_lgd_mult": 1.05, "macro_prepay_mult": 0.95, "bank_risk_appetite_mult": 0.95, "demand_mult": 0.92, "user_conversion_mult": 0.80, "user_delinquency_mult": 1.35, "complaints_mult": 1.70, "funding_spread_bps": 50 }
  ],
  "mc": { "n_sims": 500, "seed": 11 }
}
